# Workers应用名称（需与Cloudflare控制台一致）
name = "fishbowl-etf-strategy-final"

# 主入口文件（核心配置，必须正确指向）
main = "main.js"

# 兼容性日期（必须使用当前或过去的日期，不能是未来时间）
# 当前部署日期为2025-08-06，使用此日期确保兼容
compatibility_date = "2025-08-06"

# 日志配置（Wrangler v4.28.0无需嵌套在[worker]下，直接顶级配置）
[observability.logs]
enabled = true
level = "info"  # 可选级别：debug/info/warn/error

# 定时触发器配置（UTC时间，对应北京时间-8小时）
[triggers]
crons = [
  "0 3 * * 1-5",  # 北京时间11:00推送股票池
  "0 6 * * 1-5",  # 北京时间14:00执行策略
  "0 8 * * 5"     # 北京时间16:00周五更新股票池
]
