name: Deploy to Cloudflare Workers
on:
  push:
    branches: [ main ]  # 当 main 分支有代码推送时，自动触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 服务器
    steps:
      - name: 拉取仓库最新代码
        uses: actions/checkout@v4  # 官方工具，拉取代码

      - name: 安装 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: 20.x  # 安装 Node.js 20 版本

      - name: 安装项目依赖和 Wrangler 工具
        run: |
          npm install  # 安装项目依赖（如 package.json 中的包）
          npm install -g wrangler  # 全局安装 Cloudflare 部署工具

      - name: 部署代码到 Cloudflare Workers
        run: wrangler deploy  # 执行部署命令
        env:
          # 从 GitHub 密钥中读取 Cloudflare 信息（安全存储，不会泄露）
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
